project_id = "gggmfhgavzworznuagzv"

[functions.generate-coloring-page]
verify_jwt = false

[functions.generate-theme]
verify_jwt = false

[functions.upload-to-r2]
verify_jwt = false

[functions.generate-story-series]
verify_jwt = false

[functions.analyze-keywords]
verify_jwt = false
