project_id = "gggmfhgavzworznuagzv"

[functions.post-to-reddit]
verify_jwt = true

[functions.verify-reddit-connection]
verify_jwt = true

[functions.get-reddit-auth-url]
verify_jwt = true

[functions.post-to-pinterest]
verify_jwt = true

[functions.auto-post-to-social]
verify_jwt = true

[functions.verify-pinterest-connection]
verify_jwt = true

[functions.generate-coloring-page]
verify_jwt = false

[functions.generate-theme]
verify_jwt = false

[functions.upload-to-r2]
verify_jwt = false

[functions.generate-story-series]
verify_jwt = false

[functions.analyze-keywords]
verify_jwt = false

[functions.generate-category-icon]
verify_jwt = false

[functions.generate-ai-coloring]
verify_jwt = false

[functions.create-checkout]
verify_jwt = true

[functions.create-payment]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.optimize-prompt]
verify_jwt = true

[functions.handle-payment-webhook]
verify_jwt = false

[functions.auto-publish-scheduled]
verify_jwt = false

[functions.auto-generate-drafts]
verify_jwt = false

[functions.generate-sitemap]
verify_jwt = false

[functions.generate-image-sitemap]
verify_jwt = false

[functions.generate-color-inspiration]
verify_jwt = false

[functions.auto-post-reddit]
verify_jwt = false
